version: '3.1'
services:
  mariadb:
    container_name: mariadb
    image: mariadb 
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mariadb_data:/var/lib/mysql    
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
    ports:
      - 8080:8080
    depends_on:
      - mariadb
networks:
  default:
    external:
      name: bdnet

