version: '3.1'
services:
  db:
    container_name: bbdd
    image: mariadb 
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: base1
      MYSQL_USER: daw
      MYSQL_PASSWORD: laboral1
     

